In [490]:
import pandas as pd
from matplotlib import pyplot as plt
import seaborn as sns
import statsmodels.formula.api as smf
import numpy as np
import plotly.graph_objects as go
from plotly.subplots import make_subplots
import json

In [491]:
bitcoin1 = pd.read_csv("Bitcoin 1.csv")
bitcoin2 = pd.read_csv("Bitcoin 2.csv")
oil = pd.read_csv("Brent Oil Futures Daily.csv")
cpi = pd.read_csv("CPIAUCSL.csv")
dow = pd.read_excel("Dow Jones Composite.xlsx")
eth1 = pd.read_csv("Ethereum 1.csv")
eth2 = pd.read_csv("Ethereum 2.csv")
eth3 = pd.read_csv("Ethereum 3.csv")
eth4 = pd.read_csv("Ethereum 4.csv")
gold = pd.read_csv("Gold Price Monthly.csv")
appl = pd.read_csv("NASDAQ APPL.csv")
amzn = pd.read_csv("NASDAQ AMZN.csv")
comp = pd.read_csv("NASDAQ Composite.csv")
googl = pd.read_csv("NASDAQ GOOGL.csv")
meta = pd.read_csv("NASDAQ META.csv")
msft = pd.read_csv("NASDAQ MSFT.csv")
nvda = pd.read_csv("NASDAQ NVDA.csv")
tsla = pd.read_csv("NASDAQ TSLA.csv")
spcomp2 = pd.read_csv("S&P Composite 2.csv")
spcomp1 = pd.read_excel("S&P Composite.xlsx")
spgold = pd.read_csv("S&P GSCI Gold Index.csv")
silver2 = pd.read_csv("Silver 2.csv")
silver1 = pd.read_csv("Silver.csv")
solana1 = pd.read_csv("Solana 1.csv")
solana2 = pd.read_csv("Solana 2.csv")
xmag = pd.read_csv("XMAG.csv")

#This cell creates my dataframes for the excel files that I assembled.

In [492]:
bitcoin1.head()

#I open bitcoin1 to look at its contents

         Date  Close/Last  Volume     Open     High      Low
0  04/06/2026     68747.8     NaN  69099.8  69103.2  68290.9
1  04/05/2026     69086.7     NaN  67128.2  69534.5  68794.0
2  04/04/2026     67136.0     NaN  66832.5  67304.3  66986.3
3  04/03/2026     66787.9     NaN  66450.7  67283.7  66284.3
4  04/02/2026     66593.2     NaN  66581.9  66991.4  66284.3

In [493]:
bitcoin1[["Date", "Close/Last"]]

#I isolate the two columns I want in bitcoin1

            Date  Close/Last
0     04/06/2026     68747.8
1     04/05/2026     69086.7
2     04/04/2026     67136.0
3     04/03/2026     66787.9
4     04/02/2026     66593.2
...          ...         ...
2298  03/12/2019      3886.0
2299  03/11/2019      3865.1
2300  03/10/2019      3915.2
2301  03/09/2019      3944.4
2302  03/08/2019      3865.9

[2303 rows x 2 columns]

In [494]:
bitcoin1 = bitcoin1[["Date", "Close/Last"]]
bitcoin1 = bitcoin1.rename(columns = {"Close/Last" : "Price"})
bitcoin1.head()

#I overwrite the larger dataframe with the two columns I want and I rename them

         Date    Price
0  04/06/2026  68747.8
1  04/05/2026  69086.7
2  04/04/2026  67136.0
3  04/03/2026  66787.9
4  04/02/2026  66593.2

In [495]:
bitcoin1["Date"] = pd.to_datetime(bitcoin1["Date"], format = "%M/%d/%Y")
bitcoin1["Date"] = bitcoin1["Date"].dt.strftime("%M-%d-%Y")
bitcoin1.head()

#I use the to_datetime function to convert the data in the "Date" column to a datetime data type and use the strftime function to format the column how I want to

         Date    Price
0  04-06-2026  68747.8
1  04-05-2026  69086.7
2  04-04-2026  67136.0
3  04-03-2026  66787.9
4  04-02-2026  66593.2

In [ ]:
bitcoin2.head()

#I repeated the same steps for bitcoin2

,Start,End,Open,High,Low,Close,Volume,Market Cap
0,2024-04-24,2024-04-25,66553.54,67070.40,63742.73,64291.07,1.384736e+11,1.294489e+12
1,2024-04-23,2024-04-24,66761.02,67174.02,65884.15,66386.61,1.408621e+11,1.308576e+12
2,2024-04-22,2024-04-23,64952.02,67180.03,64598.00,66818.89,1.400725e+11,1.299703e+12
3,2024-04-21,2024-04-22,64875.75,65638.74,64302.47,64896.87,1.326574e+11,1.278730e+12
4,2024-04-20,2024-04-21,63824.06,65351.33,63321.19,64857.99,1.537410e+11,1.263725e+12

In [497]:
bitcoin2[["Start", "Close"]].head()

        Start     Close
0  2024-04-24  64291.07
1  2024-04-23  66386.61
2  2024-04-22  66818.89
3  2024-04-21  64896.87
4  2024-04-20  64857.99

In [498]:
bitcoin2 = bitcoin2[["Start", "Close"]]
bitcoin2 = bitcoin2.rename(columns = {"Start" : "Date", "Close" : "Price"})
bitcoin2.head()

         Date     Price
0  2024-04-24  64291.07
1  2024-04-23  66386.61
2  2024-04-22  66818.89
3  2024-04-21  64896.87
4  2024-04-20  64857.99

In [499]:
bitcoin2["Date"] = pd.to_datetime(bitcoin2["Date"], format = "%Y-%M-%d")
bitcoin2["Date"] = bitcoin2["Date"].dt.strftime("%M-%d-%Y")
bitcoin2.head()

         Date     Price
0  04-24-2024  64291.07
1  04-23-2024  66386.61
2  04-22-2024  66818.89
3  04-21-2024  64896.87
4  04-20-2024  64857.99

In [ ]:
bitcoin = bitcoin1.combine_first(bitcoin2)
bitcoin

#I used the combine_first function to combine the two dataframes into one, thus filling in the data that each was missing.

            Date       Price
0     04-06-2026  68747.8000
1     04-05-2026  69086.7000
2     04-04-2026  67136.0000
3     04-03-2026  66787.9000
4     04-02-2026  66593.2000
...          ...         ...
5016  07-31-2010      0.0679
5017  07-30-2010      0.0627
5018  07-29-2010      0.0699
5019  07-28-2010      0.0589
5020  07-27-2010      0.0600

[5021 rows x 2 columns]

I plan to repeat this process with every dataset to prepare them for analysis. Because I had only a couple hours, I focused on only wrangling one pair of datasets to use as an example. The rest will likely be easier for me now that I have actually done the process once.