In [4829]:
import pandas as pd
from matplotlib import pyplot as plt
import seaborn as sns
import statsmodels.formula.api as smf
import numpy as np
import plotly.graph_objects as go
from plotly.subplots import make_subplots
import json

In [4830]:
bitcoin1 = pd.read_csv("Bitcoin 1.csv")
bitcoin2 = pd.read_csv("Bitcoin 2.csv")
oil = pd.read_csv("Brent Oil Futures Daily.csv")
cpi = pd.read_csv("CPIAUCSL.csv")
dow = pd.read_excel("Dow Jones Composite.xlsx")
eth1 = pd.read_csv("Ethereum 1.csv")
eth2 = pd.read_csv("Ethereum 2.csv")
eth3 = pd.read_csv("Ethereum 3.csv")
eth4 = pd.read_csv("Ethereum 4.csv")
gold = pd.read_csv("Gold Price Monthly.csv")
appl = pd.read_csv("NASDAQ APPL.csv")
amzn = pd.read_csv("NASDAQ AMZN.csv")
comp = pd.read_csv("NASDAQ Composite.csv")
googl = pd.read_csv("NASDAQ GOOGL.csv")
meta = pd.read_csv("NASDAQ META.csv")
msft = pd.read_csv("NASDAQ MSFT.csv")
nvda = pd.read_csv("NASDAQ NVDA.csv")
tsla = pd.read_csv("NASDAQ TSLA.csv")
spcomp2 = pd.read_csv("S&P Composite 2.csv")
spcomp1 = pd.read_excel("S&P Composite.xlsx")
spgold = pd.read_csv("S&P GSCI Gold Index.csv")
silver2 = pd.read_csv("Silver 2.csv")
silver1 = pd.read_csv("Silver.csv")
solana1 = pd.read_csv("Solana 1.csv")
solana2 = pd.read_csv("Solana 2.csv")
xmag = pd.read_csv("XMAG.csv")

#This cell creates my dataframes for the excel files that I assembled.

In [4831]:
bitcoin1.head()

#I open bitcoin1 to look at its contents

         Date  Close/Last  Volume     Open     High      Low
0  04/06/2026     68747.8     NaN  69099.8  69103.2  68290.9
1  04/05/2026     69086.7     NaN  67128.2  69534.5  68794.0
2  04/04/2026     67136.0     NaN  66832.5  67304.3  66986.3
3  04/03/2026     66787.9     NaN  66450.7  67283.7  66284.3
4  04/02/2026     66593.2     NaN  66581.9  66991.4  66284.3

In [4832]:
bitcoin1[["Date", "Close/Last"]]

#I isolate the two columns I want in bitcoin1

            Date  Close/Last
0     04/06/2026     68747.8
1     04/05/2026     69086.7
2     04/04/2026     67136.0
3     04/03/2026     66787.9
4     04/02/2026     66593.2
...          ...         ...
2298  03/12/2019      3886.0
2299  03/11/2019      3865.1
2300  03/10/2019      3915.2
2301  03/09/2019      3944.4
2302  03/08/2019      3865.9

[2303 rows x 2 columns]

In [4833]:
bitcoin1 = bitcoin1[["Date", "Close/Last"]]
bitcoin1 = bitcoin1.rename(columns = {"Close/Last" : "Price"})
bitcoin1.head()

#I overwrite the larger dataframe with the two columns I want and I rename them

         Date    Price
0  04/06/2026  68747.8
1  04/05/2026  69086.7
2  04/04/2026  67136.0
3  04/03/2026  66787.9
4  04/02/2026  66593.2

In [4834]:
bitcoin1["Date"] = pd.to_datetime(bitcoin1["Date"], format = "%M/%d/%Y")
bitcoin1["Date"] = bitcoin1["Date"].dt.strftime("%M-%d-%Y")
bitcoin1.head()

#I use the to_datetime function to convert the data in the "Date" column to a datetime data type and use the strftime function to format the column how I want to

         Date    Price
0  04-06-2026  68747.8
1  04-05-2026  69086.7
2  04-04-2026  67136.0
3  04-03-2026  66787.9
4  04-02-2026  66593.2

In [4835]:
bitcoin2.head()

#I repeated the same steps for bitcoin2

,Start,End,Open,High,Low,Close,Volume,Market Cap
0,2024-04-24,2024-04-25,66553.54,67070.40,63742.73,64291.07,1.384736e+11,1.294489e+12
1,2024-04-23,2024-04-24,66761.02,67174.02,65884.15,66386.61,1.408621e+11,1.308576e+12
2,2024-04-22,2024-04-23,64952.02,67180.03,64598.00,66818.89,1.400725e+11,1.299703e+12
3,2024-04-21,2024-04-22,64875.75,65638.74,64302.47,64896.87,1.326574e+11,1.278730e+12
4,2024-04-20,2024-04-21,63824.06,65351.33,63321.19,64857.99,1.537410e+11,1.263725e+12

In [4836]:
bitcoin2[["Start", "Close"]].head()

        Start     Close
0  2024-04-24  64291.07
1  2024-04-23  66386.61
2  2024-04-22  66818.89
3  2024-04-21  64896.87
4  2024-04-20  64857.99

In [4837]:
bitcoin2 = bitcoin2[["Start", "Close"]]
bitcoin2 = bitcoin2.rename(columns = {"Start" : "Date", "Close" : "Price"})
bitcoin2.head()

         Date     Price
0  2024-04-24  64291.07
1  2024-04-23  66386.61
2  2024-04-22  66818.89
3  2024-04-21  64896.87
4  2024-04-20  64857.99

In [4838]:
bitcoin2["Date"] = pd.to_datetime(bitcoin2["Date"], format = "%Y-%M-%d")
bitcoin2["Date"] = bitcoin2["Date"].dt.strftime("%M-%d-%Y")
bitcoin2.head()

         Date     Price
0  04-24-2024  64291.07
1  04-23-2024  66386.61
2  04-22-2024  66818.89
3  04-21-2024  64896.87
4  04-20-2024  64857.99

In [4839]:
bitcoin = bitcoin1.combine_first(bitcoin2)
bitcoin

#I used the combine_first function to combine the two dataframes into one, thus filling in the data that each was missing.

            Date       Price
0     04-06-2026  68747.8000
1     04-05-2026  69086.7000
2     04-04-2026  67136.0000
3     04-03-2026  66787.9000
4     04-02-2026  66593.2000
...          ...         ...
5016  07-31-2010      0.0679
5017  07-30-2010      0.0627
5018  07-29-2010      0.0699
5019  07-28-2010      0.0589
5020  07-27-2010      0.0600

[5021 rows x 2 columns]

I plan to repeat this process with every dataset to prepare them for analysis. Because I had only a couple hours, I focused on only wrangling one pair of datasets to use as an example. The rest will likely be easier for me now that I have actually done the process once.

In [4840]:
oil

            Date   Price
0     1987-05-20   18.63
1     1987-05-21   18.45
2     1987-05-22   18.55
3     1987-05-25   18.60
4     1987-05-26   18.63
...          ...     ...
9856  2026-03-24  108.42
9857  2026-03-25  109.14
9858  2026-03-26  113.39
9859  2026-03-27  121.47
9860  2026-03-30  121.88

[9861 rows x 2 columns]

In [4841]:
oil["Date"] = pd.to_datetime(oil["Date"], format = "%Y-%M-%d")
oil["Date"] = oil["Date"].dt.strftime("%M-%d-%Y")
oil

            Date   Price
0     05-20-1987   18.63
1     05-21-1987   18.45
2     05-22-1987   18.55
3     05-25-1987   18.60
4     05-26-1987   18.63
...          ...     ...
9856  03-24-2026  108.42
9857  03-25-2026  109.14
9858  03-26-2026  113.39
9859  03-27-2026  121.47
9860  03-30-2026  121.88

[9861 rows x 2 columns]

In [4842]:
cpi

    observation_date  CPIAUCSL
0         1947-01-01    21.480
1         1947-02-01    21.620
2         1947-03-01    22.000
3         1947-04-01    22.000
4         1947-05-01    21.950
..               ...       ...
945       2025-10-01       NaN
946       2025-11-01   325.063
947       2025-12-01   326.031
948       2026-01-01   326.588
949       2026-02-01   327.460

[950 rows x 2 columns]

In [4843]:
cpi = cpi.rename(columns = {"observation_date" : "Month", "CPIAUCSL" : "Rate"})
cpi.head()

        Month   Rate
0  1947-01-01  21.48
1  1947-02-01  21.62
2  1947-03-01  22.00
3  1947-04-01  22.00
4  1947-05-01  21.95

In [4844]:
cpi["Month"] = pd.to_datetime(cpi["Month"], format = "%Y-%M-%d")
cpi["Month"] = cpi["Month"].dt.strftime("%M-%d-%Y")
cpi

          Month     Rate
0    01-01-1947   21.480
1    02-01-1947   21.620
2    03-01-1947   22.000
3    04-01-1947   22.000
4    05-01-1947   21.950
..          ...      ...
945  10-01-2025      NaN
946  11-01-2025  325.063
947  12-01-2025  326.031
948  01-01-2026  326.588
949  02-01-2026  327.460

[950 rows x 2 columns]

In [4845]:
dow

                                             Unnamed: 0    Unnamed: 1
0                                                   NaN           NaN
1                                                   NaN           NaN
2                                                As of:  Apr 06, 2026
3                                                   NaN           NaN
4                                                   NaN           NaN
...                                                 ...           ...
2523                                2026-04-06 00:00:00      46669.88
2524                                                NaN           NaN
2525                                                NaN           NaN
2526                                                NaN           NaN
2527  DISCLAIMER\n\nPERFORMANCE DISCLOSURE/BACK-TEST...           NaN

[2528 rows x 2 columns]

In [4846]:
dow = pd.read_excel("Dow Jones Composite.xlsx", skiprows = 6, nrows = 2519, usecols = "A:B")
dow

#Here, I reformatted the dow dataframe to better reflect the data and not be affected by the whitespace in the file

     Effective date   Dow Jones Industrial Average
0         2016-03-31                      17685.09
1         2016-04-01                      17792.75
2         2016-04-04                      17737.00
3         2016-04-05                      17603.32
4         2016-04-06                      17716.05
...              ...                           ...
2513      2026-03-30                      45216.14
2514      2026-03-31                      46341.51
2515      2026-04-01                      46565.74
2516      2026-04-02                      46504.67
2517      2026-04-06                      46669.88

[2518 rows x 2 columns]

In [4847]:
dow = dow.rename(columns = {"Effective date " : "Date", "Dow Jones Industrial Average" : "Price"})
dow

           Date     Price
0    2016-03-31  17685.09
1    2016-04-01  17792.75
2    2016-04-04  17737.00
3    2016-04-05  17603.32
4    2016-04-06  17716.05
...         ...       ...
2513 2026-03-30  45216.14
2514 2026-03-31  46341.51
2515 2026-04-01  46565.74
2516 2026-04-02  46504.67
2517 2026-04-06  46669.88

[2518 rows x 2 columns]

In [4848]:
dow["Date"] = pd.to_datetime(dow["Date"], format = "%Y-%M-%d")
dow["Date"] = dow["Date"].dt.strftime("%m-%d-%Y")
dow

            Date     Price
0     03-31-2016  17685.09
1     04-01-2016  17792.75
2     04-04-2016  17737.00
3     04-05-2016  17603.32
4     04-06-2016  17716.05
...          ...       ...
2513  03-30-2026  45216.14
2514  03-31-2026  46341.51
2515  04-01-2026  46565.74
2516  04-02-2026  46504.67
2517  04-06-2026  46669.88

[2518 rows x 2 columns]

In [4849]:
eth1

,Date,Open,High,Low,Close,Adj Close,Volume
0,2015-08-08,2.793760,2.798810,0.714725,0.753325,0.753325,6.741880e+05
1,2015-08-09,0.706136,0.879810,0.629191,0.701897,0.701897,5.321700e+05
2,2015-08-10,0.713989,0.729854,0.636546,0.708448,0.708448,4.052830e+05
3,2015-08-11,0.708087,1.131410,0.663235,1.067860,1.067860,1.463100e+06
4,2015-08-12,1.058750,1.289940,0.883608,1.217440,1.217440,2.150620e+06
...,...,...,...,...,...,...,...
2115,2021-05-23,2298.367188,2384.411621,1737.468750,2109.579834,2109.579834,5.600572e+10
2116,2021-05-24,2099.936035,2672.595703,2090.639648,2643.591064,2643.591064,5.369712e+10
2117,2021-05-25,2649.033203,2750.534912,2394.355469,2706.628906,2706.628906,4.955833e+10
2118,2021-05-26,2707.052734,2911.735596,2652.094482,2888.698730,2888.698730,4.249977e+10
2119,2021-05-27,2872.692383,2872.692383,2642.607910,2776.133057,2776.133057,3.456504e+10

In [4850]:
eth1 = eth1[["Date", "Close"]]
eth1 = eth1.rename(columns = {"Close" : "Price"})
eth1

            Date        Price
0     2015-08-08     0.753325
1     2015-08-09     0.701897
2     2015-08-10     0.708448
3     2015-08-11     1.067860
4     2015-08-12     1.217440
...          ...          ...
2115  2021-05-23  2109.579834
2116  2021-05-24  2643.591064
2117  2021-05-25  2706.628906
2118  2021-05-26  2888.698730
2119  2021-05-27  2776.133057

[2120 rows x 2 columns]

In [4851]:
eth1["Date"] = pd.to_datetime(eth1["Date"], format = "%Y-%M-%d")
eth1["Date"] = eth1["Date"].dt.strftime("%m-%d-%Y")
eth1

            Date        Price
0     01-08-2015     0.753325
1     01-09-2015     0.701897
2     01-10-2015     0.708448
3     01-11-2015     1.067860
4     01-12-2015     1.217440
...          ...          ...
2115  01-23-2021  2109.579834
2116  01-24-2021  2643.591064
2117  01-25-2021  2706.628906
2118  01-26-2021  2888.698730
2119  01-27-2021  2776.133057

[2120 rows x 2 columns]

In [4852]:
eth2

              Date     Price      Open      High       Low      Vol Change %
0     May 06, 2023  1,969.82  1,993.33  2,013.10  1,964.43  641.57K   -1.18%
1     May 05, 2023  1,993.33  1,877.06  1,996.64  1,875.66  589.05K    6.19%
2     May 04, 2023  1,877.06  1,904.76  1,915.15  1,868.18  372.69K   -1.45%
3     May 03, 2023  1,904.74  1,869.74  1,915.00  1,844.72  489.66K    1.87%
4     May 02, 2023  1,869.74  1,830.75  1,878.70  1,823.25  391.27K    2.13%
...            ...       ...       ...       ...       ...      ...      ...
2609  Mar 14, 2016      12.5     15.07     15.07      11.4   92.18K  -17.05%
2610  Mar 13, 2016     15.07     12.92     15.07     12.92    1.30K   16.64%
2611  Mar 12, 2016     12.92     11.95     13.45     11.95    0.83K    8.12%
2612  Mar 11, 2016     11.95     11.75     11.95     11.75    0.18K    1.70%
2613  Mar 10, 2016     11.75      11.2     11.85     11.07    0.00K    4.91%

[2614 rows x 7 columns]

In [4853]:
eth2 = eth2.iloc[::-1]
eth2

              Date     Price      Open      High       Low      Vol Change %
2613  Mar 10, 2016     11.75      11.2     11.85     11.07    0.00K    4.91%
2612  Mar 11, 2016     11.95     11.75     11.95     11.75    0.18K    1.70%
2611  Mar 12, 2016     12.92     11.95     13.45     11.95    0.83K    8.12%
2610  Mar 13, 2016     15.07     12.92     15.07     12.92    1.30K   16.64%
2609  Mar 14, 2016      12.5     15.07     15.07      11.4   92.18K  -17.05%
...            ...       ...       ...       ...       ...      ...      ...
4     May 02, 2023  1,869.74  1,830.75  1,878.70  1,823.25  391.27K    2.13%
3     May 03, 2023  1,904.74  1,869.74  1,915.00  1,844.72  489.66K    1.87%
2     May 04, 2023  1,877.06  1,904.76  1,915.15  1,868.18  372.69K   -1.45%
1     May 05, 2023  1,993.33  1,877.06  1,996.64  1,875.66  589.05K    6.19%
0     May 06, 2023  1,969.82  1,993.33  2,013.10  1,964.43  641.57K   -1.18%

[2614 rows x 7 columns]

In [4854]:
eth2 = eth2[["Date", "Price"]]
eth2

              Date     Price
2613  Mar 10, 2016     11.75
2612  Mar 11, 2016     11.95
2611  Mar 12, 2016     12.92
2610  Mar 13, 2016     15.07
2609  Mar 14, 2016      12.5
...            ...       ...
4     May 02, 2023  1,869.74
3     May 03, 2023  1,904.74
2     May 04, 2023  1,877.06
1     May 05, 2023  1,993.33
0     May 06, 2023  1,969.82

[2614 rows x 2 columns]

In [4855]:
eth2["Date"] = pd.to_datetime(eth2["Date"], format = "%b %d, %Y")
eth2["Date"] = eth2["Date"].dt.strftime("%m-%d-%Y")
eth2

/var/folders/_k/hbpmd3cn3cl4dn7css2gnbv80000gp/T/ipykernel_5258/4138373936.py:1: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  eth2["Date"] = pd.to_datetime(eth2["Date"], format = "%b %d, %Y")
/var/folders/_k/hbpmd3cn3cl4dn7css2gnbv80000gp/T/ipykernel_5258/4138373936.py:2: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  eth2["Date"] = eth2["Date"].dt.strftime("%m-%d-%Y")

            Date     Price
2613  03-10-2016     11.75
2612  03-11-2016     11.95
2611  03-12-2016     12.92
2610  03-13-2016     15.07
2609  03-14-2016      12.5
...          ...       ...
4     05-02-2023  1,869.74
3     05-03-2023  1,904.74
2     05-04-2023  1,877.06
1     05-05-2023  1,993.33
0     05-06-2023  1,969.82

[2614 rows x 2 columns]

In [4856]:
eth3

       datetime     open     high      low    close        volume
0     8/17/2017   301.13   312.18   298.00   302.00    7030.71034
1     8/18/2017   302.00   311.79   283.94   293.96    9537.84646
2     8/19/2017   293.31   299.90   278.00   290.91    2146.19773
3     8/20/2017   289.41   300.53   282.85   299.10    2510.13871
4     8/21/2017   299.10   346.52   294.60   323.29    5219.44542
...         ...      ...      ...      ...      ...           ...
2396   3/9/2024  3883.37  3942.00  3870.01  3905.21  254839.13860
2397  3/10/2024  3905.20  3964.67  3791.26  3878.47  356664.68000
2398  3/11/2024  3878.47  4086.23  3722.95  4064.80  721554.51390
2399  3/12/2024  4064.80  4093.92  3828.98  3979.96  632787.39410
2400  3/13/2024  3979.97  4083.00  3932.23  4004.79  482305.77660

[2401 rows x 6 columns]

In [4857]:
eth3 = eth3[["datetime", "close"]]
eth3

       datetime    close
0     8/17/2017   302.00
1     8/18/2017   293.96
2     8/19/2017   290.91
3     8/20/2017   299.10
4     8/21/2017   323.29
...         ...      ...
2396   3/9/2024  3905.21
2397  3/10/2024  3878.47
2398  3/11/2024  4064.80
2399  3/12/2024  3979.96
2400  3/13/2024  4004.79

[2401 rows x 2 columns]

In [4858]:
eth3 = eth3.rename(columns = {"datetime" : "Date", "close" : "Price"})
eth3

           Date    Price
0     8/17/2017   302.00
1     8/18/2017   293.96
2     8/19/2017   290.91
3     8/20/2017   299.10
4     8/21/2017   323.29
...         ...      ...
2396   3/9/2024  3905.21
2397  3/10/2024  3878.47
2398  3/11/2024  4064.80
2399  3/12/2024  3979.96
2400  3/13/2024  4004.79

[2401 rows x 2 columns]

In [4859]:
eth3["Date"] = pd.to_datetime(eth3["Date"], format = "%m/%d/%Y")
eth3["Date"] = eth3["Date"].dt.strftime("%m-%d-%Y")
eth3

            Date    Price
0     08-17-2017   302.00
1     08-18-2017   293.96
2     08-19-2017   290.91
3     08-20-2017   299.10
4     08-21-2017   323.29
...          ...      ...
2396  03-09-2024  3905.21
2397  03-10-2024  3878.47
2398  03-11-2024  4064.80
2399  03-12-2024  3979.96
2400  03-13-2024  4004.79

[2401 rows x 2 columns]

In [4860]:
eth4

            Date  Close/Last  Volume     Open     High      Low
0     04/06/2026     2107.81     NaN  2128.73  2119.17  2093.82
1     04/05/2026     2128.30     NaN  2056.47  2143.83  2110.33
2     04/04/2026     2056.71     NaN  2050.01  2065.51  2054.37
3     04/03/2026     2058.10     NaN  2038.58  2074.69  2042.35
4     04/02/2026     2052.71     NaN  2056.78  2062.47  2042.35
...          ...         ...     ...      ...      ...      ...
2298  03/12/2019      133.80     NaN   132.99   134.93   129.14
2299  03/11/2019      133.42     NaN   136.10   136.23   131.66
2300  03/10/2019      135.72     NaN   137.52   137.75   134.53
2301  03/09/2019      137.52     NaN   133.85   138.57   133.38
2302  03/08/2019      133.85     NaN   136.93   139.45   131.66

[2303 rows x 6 columns]

In [4861]:
eth4 = eth4.iloc[::-1]
eth4

            Date  Close/Last  Volume     Open     High      Low
2302  03/08/2019      133.85     NaN   136.93   139.45   131.66
2301  03/09/2019      137.52     NaN   133.85   138.57   133.38
2300  03/10/2019      135.72     NaN   137.52   137.75   134.53
2299  03/11/2019      133.42     NaN   136.10   136.23   131.66
2298  03/12/2019      133.80     NaN   132.99   134.93   129.14
...          ...         ...     ...      ...      ...      ...
4     04/02/2026     2052.71     NaN  2056.78  2062.47  2042.35
3     04/03/2026     2058.10     NaN  2038.58  2074.69  2042.35
2     04/04/2026     2056.71     NaN  2050.01  2065.51  2054.37
1     04/05/2026     2128.30     NaN  2056.47  2143.83  2110.33
0     04/06/2026     2107.81     NaN  2128.73  2119.17  2093.82

[2303 rows x 6 columns]

In [4862]:
eth4 = eth4[["Date", "Close/Last"]]
eth4 = eth4.rename(columns = {"Close/Last" : "Price"})
eth4

            Date    Price
2302  03/08/2019   133.85
2301  03/09/2019   137.52
2300  03/10/2019   135.72
2299  03/11/2019   133.42
2298  03/12/2019   133.80
...          ...      ...
4     04/02/2026  2052.71
3     04/03/2026  2058.10
2     04/04/2026  2056.71
1     04/05/2026  2128.30
0     04/06/2026  2107.81

[2303 rows x 2 columns]

In [4863]:
eth4["Date"] = pd.to_datetime(eth4["Date"], format = "%m/%d/%Y")
eth4["Date"] = eth4["Date"].dt.strftime("%m-%d-%Y")
eth4

            Date    Price
2302  03-08-2019   133.85
2301  03-09-2019   137.52
2300  03-10-2019   135.72
2299  03-11-2019   133.42
2298  03-12-2019   133.80
...          ...      ...
4     04-02-2026  2052.71
3     04-03-2026  2058.10
2     04-04-2026  2056.71
1     04-05-2026  2128.30
0     04-06-2026  2107.81

[2303 rows x 2 columns]

In [ ]:
eth = eth1.combine_first(eth2)
eth
#This is not working

            Date     Price
0     01-08-2015  0.753325
1     01-09-2015  0.701897
2     01-10-2015  0.708448
3     01-11-2015   1.06786
4     01-12-2015   1.21744
...          ...       ...
2609  03-14-2016      12.5
2610  03-13-2016     15.07
2611  03-12-2016     12.92
2612  03-11-2016     11.95
2613  03-10-2016     11.75

[2614 rows x 2 columns]