In [8086]:
import pandas as pd
from matplotlib import pyplot as plt
import seaborn as sns
import statsmodels.formula.api as smf
import numpy as np
import plotly.graph_objects as go
from plotly.subplots import make_subplots
import json

In [8087]:
bitcoin1 = pd.read_csv("Bitcoin 1.csv")
bitcoin2 = pd.read_csv("Bitcoin 2.csv")
oil = pd.read_csv("Brent Oil Futures Daily.csv")
cpi = pd.read_csv("CPIAUCSL.csv")
dow = pd.read_excel("Dow Jones Composite.xlsx")
eth1 = pd.read_csv("Ethereum 1.csv")
eth2 = pd.read_csv("Ethereum 2.csv")
eth3 = pd.read_csv("Ethereum 3.csv")
eth4 = pd.read_csv("Ethereum 4.csv")
gold = pd.read_csv("Gold New.csv")
appl = pd.read_csv("NASDAQ APPL.csv")
amzn = pd.read_csv("NASDAQ AMZN.csv")
comp = pd.read_csv("NASDAQ Composite.csv")
googl = pd.read_csv("NASDAQ GOOGL.csv")
meta = pd.read_csv("NASDAQ META.csv")
msft = pd.read_csv("NASDAQ MSFT.csv")
nvda = pd.read_csv("NASDAQ NVDA.csv")
tsla = pd.read_csv("NASDAQ TSLA.csv")
spcomp2 = pd.read_csv("S&P Composite 2.csv")
spcomp1 = pd.read_excel("S&P Composite.xlsx")
spgold = pd.read_csv("S&P GSCI Gold Index.csv")
silver2 = pd.read_csv("Silver 2.csv")
silver1 = pd.read_csv("Silver.csv")
solana1 = pd.read_csv("Solana 1.csv")
solana2 = pd.read_csv("Solana 2.csv")
xmag = pd.read_csv("XMAG.csv")

#This cell creates my dataframes for the excel files that I assembled.

In [8088]:
bitcoin1.head()

#I open bitcoin1 to look at its contents

         Date  Close/Last  Volume     Open     High      Low
0  04/06/2026     68747.8     NaN  69099.8  69103.2  68290.9
1  04/05/2026     69086.7     NaN  67128.2  69534.5  68794.0
2  04/04/2026     67136.0     NaN  66832.5  67304.3  66986.3
3  04/03/2026     66787.9     NaN  66450.7  67283.7  66284.3
4  04/02/2026     66593.2     NaN  66581.9  66991.4  66284.3

In [8089]:
bitcoin1[["Date", "Close/Last"]]

#I isolate the two columns I want in bitcoin1

            Date  Close/Last
0     04/06/2026     68747.8
1     04/05/2026     69086.7
2     04/04/2026     67136.0
3     04/03/2026     66787.9
4     04/02/2026     66593.2
...          ...         ...
2298  03/12/2019      3886.0
2299  03/11/2019      3865.1
2300  03/10/2019      3915.2
2301  03/09/2019      3944.4
2302  03/08/2019      3865.9

[2303 rows x 2 columns]

In [8090]:
bitcoin1 = bitcoin1[["Date", "Close/Last"]]
bitcoin1 = bitcoin1.rename(columns = {"Close/Last" : "Price"})
bitcoin1.head()

#I overwrite the larger dataframe with the two columns I want and I rename them

         Date    Price
0  04/06/2026  68747.8
1  04/05/2026  69086.7
2  04/04/2026  67136.0
3  04/03/2026  66787.9
4  04/02/2026  66593.2

In [8091]:
bitcoin1["Date"] = pd.to_datetime(bitcoin1["Date"], format = "%M/%d/%Y")
bitcoin1["Date"] = bitcoin1["Date"].dt.strftime("%M-%d-%Y")
bitcoin1.head()

#I use the to_datetime function to convert the data in the "Date" column to a datetime data type and use the strftime function to format the column how I want to

         Date    Price
0  04-06-2026  68747.8
1  04-05-2026  69086.7
2  04-04-2026  67136.0
3  04-03-2026  66787.9
4  04-02-2026  66593.2

In [8092]:
bitcoin2.head()

#I repeated the same steps for bitcoin2

,Start,End,Open,High,Low,Close,Volume,Market Cap
0,2024-04-24,2024-04-25,66553.54,67070.40,63742.73,64291.07,1.384736e+11,1.294489e+12
1,2024-04-23,2024-04-24,66761.02,67174.02,65884.15,66386.61,1.408621e+11,1.308576e+12
2,2024-04-22,2024-04-23,64952.02,67180.03,64598.00,66818.89,1.400725e+11,1.299703e+12
3,2024-04-21,2024-04-22,64875.75,65638.74,64302.47,64896.87,1.326574e+11,1.278730e+12
4,2024-04-20,2024-04-21,63824.06,65351.33,63321.19,64857.99,1.537410e+11,1.263725e+12

In [8093]:
bitcoin2[["Start", "Close"]].head()

        Start     Close
0  2024-04-24  64291.07
1  2024-04-23  66386.61
2  2024-04-22  66818.89
3  2024-04-21  64896.87
4  2024-04-20  64857.99

In [8094]:
bitcoin2 = bitcoin2[["Start", "Close"]]
bitcoin2 = bitcoin2.rename(columns = {"Start" : "Date", "Close" : "Price"})
bitcoin2.head()

         Date     Price
0  2024-04-24  64291.07
1  2024-04-23  66386.61
2  2024-04-22  66818.89
3  2024-04-21  64896.87
4  2024-04-20  64857.99

In [8095]:
bitcoin2["Date"] = pd.to_datetime(bitcoin2["Date"], format = "%Y-%M-%d")
bitcoin2["Date"] = bitcoin2["Date"].dt.strftime("%M-%d-%Y")
bitcoin2.head()

         Date     Price
0  04-24-2024  64291.07
1  04-23-2024  66386.61
2  04-22-2024  66818.89
3  04-21-2024  64896.87
4  04-20-2024  64857.99

In [8096]:
bitcoin = bitcoin1.combine_first(bitcoin2)
bitcoin

#I used the combine_first function to combine the two dataframes into one, thus filling in the data that each was missing.

            Date       Price
0     04-06-2026  68747.8000
1     04-05-2026  69086.7000
2     04-04-2026  67136.0000
3     04-03-2026  66787.9000
4     04-02-2026  66593.2000
...          ...         ...
5016  07-31-2010      0.0679
5017  07-30-2010      0.0627
5018  07-29-2010      0.0699
5019  07-28-2010      0.0589
5020  07-27-2010      0.0600

[5021 rows x 2 columns]

I plan to repeat this process with every dataset to prepare them for analysis. Because I had only a couple hours, I focused on only wrangling one pair of datasets to use as an example. The rest will likely be easier for me now that I have actually done the process once.

In [8097]:
oil

            Date   Price
0     1987-05-20   18.63
1     1987-05-21   18.45
2     1987-05-22   18.55
3     1987-05-25   18.60
4     1987-05-26   18.63
...          ...     ...
9856  2026-03-24  108.42
9857  2026-03-25  109.14
9858  2026-03-26  113.39
9859  2026-03-27  121.47
9860  2026-03-30  121.88

[9861 rows x 2 columns]

In [8098]:
oil["Date"] = pd.to_datetime(oil["Date"], format = "%Y-%M-%d")
oil["Date"] = oil["Date"].dt.strftime("%M-%d-%Y")
oil

            Date   Price
0     05-20-1987   18.63
1     05-21-1987   18.45
2     05-22-1987   18.55
3     05-25-1987   18.60
4     05-26-1987   18.63
...          ...     ...
9856  03-24-2026  108.42
9857  03-25-2026  109.14
9858  03-26-2026  113.39
9859  03-27-2026  121.47
9860  03-30-2026  121.88

[9861 rows x 2 columns]

In [8099]:
cpi

    observation_date  CPIAUCSL
0         1947-01-01    21.480
1         1947-02-01    21.620
2         1947-03-01    22.000
3         1947-04-01    22.000
4         1947-05-01    21.950
..               ...       ...
945       2025-10-01       NaN
946       2025-11-01   325.063
947       2025-12-01   326.031
948       2026-01-01   326.588
949       2026-02-01   327.460

[950 rows x 2 columns]

In [8100]:
cpi = cpi.rename(columns = {"observation_date" : "Month", "CPIAUCSL" : "Rate"})
cpi.head()

        Month   Rate
0  1947-01-01  21.48
1  1947-02-01  21.62
2  1947-03-01  22.00
3  1947-04-01  22.00
4  1947-05-01  21.95

In [8101]:
cpi["Month"] = pd.to_datetime(cpi["Month"], format = "%Y-%M-%d")
cpi["Month"] = cpi["Month"].dt.strftime("%M-%d-%Y")
cpi

          Month     Rate
0    01-01-1947   21.480
1    02-01-1947   21.620
2    03-01-1947   22.000
3    04-01-1947   22.000
4    05-01-1947   21.950
..          ...      ...
945  10-01-2025      NaN
946  11-01-2025  325.063
947  12-01-2025  326.031
948  01-01-2026  326.588
949  02-01-2026  327.460

[950 rows x 2 columns]

In [8102]:
dow

                                             Unnamed: 0    Unnamed: 1
0                                                   NaN           NaN
1                                                   NaN           NaN
2                                                As of:  Apr 06, 2026
3                                                   NaN           NaN
4                                                   NaN           NaN
...                                                 ...           ...
2523                                2026-04-06 00:00:00      46669.88
2524                                                NaN           NaN
2525                                                NaN           NaN
2526                                                NaN           NaN
2527  DISCLAIMER\n\nPERFORMANCE DISCLOSURE/BACK-TEST...           NaN

[2528 rows x 2 columns]

In [8103]:
dow = pd.read_excel("Dow Jones Composite.xlsx", skiprows = 6, nrows = 2519, usecols = "A:B")
dow

#Here, I reformatted the dow dataframe to better reflect the data and not be affected by the whitespace in the file

     Effective date   Dow Jones Industrial Average
0         2016-03-31                      17685.09
1         2016-04-01                      17792.75
2         2016-04-04                      17737.00
3         2016-04-05                      17603.32
4         2016-04-06                      17716.05
...              ...                           ...
2513      2026-03-30                      45216.14
2514      2026-03-31                      46341.51
2515      2026-04-01                      46565.74
2516      2026-04-02                      46504.67
2517      2026-04-06                      46669.88

[2518 rows x 2 columns]

In [8104]:
dow = dow.rename(columns = {"Effective date " : "Date", "Dow Jones Industrial Average" : "Price"})
dow

           Date     Price
0    2016-03-31  17685.09
1    2016-04-01  17792.75
2    2016-04-04  17737.00
3    2016-04-05  17603.32
4    2016-04-06  17716.05
...         ...       ...
2513 2026-03-30  45216.14
2514 2026-03-31  46341.51
2515 2026-04-01  46565.74
2516 2026-04-02  46504.67
2517 2026-04-06  46669.88

[2518 rows x 2 columns]

In [8105]:
dow["Date"] = pd.to_datetime(dow["Date"], format = "%Y-%M-%d")
dow["Date"] = dow["Date"].dt.strftime("%m-%d-%Y")
dow

            Date     Price
0     03-31-2016  17685.09
1     04-01-2016  17792.75
2     04-04-2016  17737.00
3     04-05-2016  17603.32
4     04-06-2016  17716.05
...          ...       ...
2513  03-30-2026  45216.14
2514  03-31-2026  46341.51
2515  04-01-2026  46565.74
2516  04-02-2026  46504.67
2517  04-06-2026  46669.88

[2518 rows x 2 columns]

In [8106]:
eth1

,Date,Open,High,Low,Close,Adj Close,Volume
0,2015-08-08,2.793760,2.798810,0.714725,0.753325,0.753325,6.741880e+05
1,2015-08-09,0.706136,0.879810,0.629191,0.701897,0.701897,5.321700e+05
2,2015-08-10,0.713989,0.729854,0.636546,0.708448,0.708448,4.052830e+05
3,2015-08-11,0.708087,1.131410,0.663235,1.067860,1.067860,1.463100e+06
4,2015-08-12,1.058750,1.289940,0.883608,1.217440,1.217440,2.150620e+06
...,...,...,...,...,...,...,...
2115,2021-05-23,2298.367188,2384.411621,1737.468750,2109.579834,2109.579834,5.600572e+10
2116,2021-05-24,2099.936035,2672.595703,2090.639648,2643.591064,2643.591064,5.369712e+10
2117,2021-05-25,2649.033203,2750.534912,2394.355469,2706.628906,2706.628906,4.955833e+10
2118,2021-05-26,2707.052734,2911.735596,2652.094482,2888.698730,2888.698730,4.249977e+10
2119,2021-05-27,2872.692383,2872.692383,2642.607910,2776.133057,2776.133057,3.456504e+10

In [8107]:
eth1 = eth1[["Date", "Close"]]
eth1 = eth1.rename(columns = {"Close" : "Price"})
eth1

            Date        Price
0     2015-08-08     0.753325
1     2015-08-09     0.701897
2     2015-08-10     0.708448
3     2015-08-11     1.067860
4     2015-08-12     1.217440
...          ...          ...
2115  2021-05-23  2109.579834
2116  2021-05-24  2643.591064
2117  2021-05-25  2706.628906
2118  2021-05-26  2888.698730
2119  2021-05-27  2776.133057

[2120 rows x 2 columns]

In [8108]:
eth1["Date"] = pd.to_datetime(eth1["Date"], format = "%Y-%M-%d")
eth1["Date"] = eth1["Date"].dt.strftime("%m-%d-%Y")
eth1

            Date        Price
0     01-08-2015     0.753325
1     01-09-2015     0.701897
2     01-10-2015     0.708448
3     01-11-2015     1.067860
4     01-12-2015     1.217440
...          ...          ...
2115  01-23-2021  2109.579834
2116  01-24-2021  2643.591064
2117  01-25-2021  2706.628906
2118  01-26-2021  2888.698730
2119  01-27-2021  2776.133057

[2120 rows x 2 columns]

In [8109]:
eth2

              Date     Price      Open      High       Low      Vol Change %
0     May 06, 2023  1,969.82  1,993.33  2,013.10  1,964.43  641.57K   -1.18%
1     May 05, 2023  1,993.33  1,877.06  1,996.64  1,875.66  589.05K    6.19%
2     May 04, 2023  1,877.06  1,904.76  1,915.15  1,868.18  372.69K   -1.45%
3     May 03, 2023  1,904.74  1,869.74  1,915.00  1,844.72  489.66K    1.87%
4     May 02, 2023  1,869.74  1,830.75  1,878.70  1,823.25  391.27K    2.13%
...            ...       ...       ...       ...       ...      ...      ...
2609  Mar 14, 2016      12.5     15.07     15.07      11.4   92.18K  -17.05%
2610  Mar 13, 2016     15.07     12.92     15.07     12.92    1.30K   16.64%
2611  Mar 12, 2016     12.92     11.95     13.45     11.95    0.83K    8.12%
2612  Mar 11, 2016     11.95     11.75     11.95     11.75    0.18K    1.70%
2613  Mar 10, 2016     11.75      11.2     11.85     11.07    0.00K    4.91%

[2614 rows x 7 columns]

In [8110]:
eth2 = eth2.iloc[::-1]
eth2 = eth2.reset_index(drop = True)
eth2

              Date     Price      Open      High       Low      Vol Change %
0     Mar 10, 2016     11.75      11.2     11.85     11.07    0.00K    4.91%
1     Mar 11, 2016     11.95     11.75     11.95     11.75    0.18K    1.70%
2     Mar 12, 2016     12.92     11.95     13.45     11.95    0.83K    8.12%
3     Mar 13, 2016     15.07     12.92     15.07     12.92    1.30K   16.64%
4     Mar 14, 2016      12.5     15.07     15.07      11.4   92.18K  -17.05%
...            ...       ...       ...       ...       ...      ...      ...
2609  May 02, 2023  1,869.74  1,830.75  1,878.70  1,823.25  391.27K    2.13%
2610  May 03, 2023  1,904.74  1,869.74  1,915.00  1,844.72  489.66K    1.87%
2611  May 04, 2023  1,877.06  1,904.76  1,915.15  1,868.18  372.69K   -1.45%
2612  May 05, 2023  1,993.33  1,877.06  1,996.64  1,875.66  589.05K    6.19%
2613  May 06, 2023  1,969.82  1,993.33  2,013.10  1,964.43  641.57K   -1.18%

[2614 rows x 7 columns]

In [8111]:
eth2 = eth2[["Date", "Price"]]
eth2

              Date     Price
0     Mar 10, 2016     11.75
1     Mar 11, 2016     11.95
2     Mar 12, 2016     12.92
3     Mar 13, 2016     15.07
4     Mar 14, 2016      12.5
...            ...       ...
2609  May 02, 2023  1,869.74
2610  May 03, 2023  1,904.74
2611  May 04, 2023  1,877.06
2612  May 05, 2023  1,993.33
2613  May 06, 2023  1,969.82

[2614 rows x 2 columns]

In [8112]:
eth2["Date"] = pd.to_datetime(eth2["Date"], format = "%b %d, %Y")
eth2["Date"] = eth2["Date"].dt.strftime("%m-%d-%Y")
eth2

/var/folders/_k/hbpmd3cn3cl4dn7css2gnbv80000gp/T/ipykernel_4023/4138373936.py:1: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  eth2["Date"] = pd.to_datetime(eth2["Date"], format = "%b %d, %Y")
/var/folders/_k/hbpmd3cn3cl4dn7css2gnbv80000gp/T/ipykernel_4023/4138373936.py:2: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  eth2["Date"] = eth2["Date"].dt.strftime("%m-%d-%Y")

            Date     Price
0     03-10-2016     11.75
1     03-11-2016     11.95
2     03-12-2016     12.92
3     03-13-2016     15.07
4     03-14-2016      12.5
...          ...       ...
2609  05-02-2023  1,869.74
2610  05-03-2023  1,904.74
2611  05-04-2023  1,877.06
2612  05-05-2023  1,993.33
2613  05-06-2023  1,969.82

[2614 rows x 2 columns]

In [8113]:
eth3

       datetime     open     high      low    close        volume
0     8/17/2017   301.13   312.18   298.00   302.00    7030.71034
1     8/18/2017   302.00   311.79   283.94   293.96    9537.84646
2     8/19/2017   293.31   299.90   278.00   290.91    2146.19773
3     8/20/2017   289.41   300.53   282.85   299.10    2510.13871
4     8/21/2017   299.10   346.52   294.60   323.29    5219.44542
...         ...      ...      ...      ...      ...           ...
2396   3/9/2024  3883.37  3942.00  3870.01  3905.21  254839.13860
2397  3/10/2024  3905.20  3964.67  3791.26  3878.47  356664.68000
2398  3/11/2024  3878.47  4086.23  3722.95  4064.80  721554.51390
2399  3/12/2024  4064.80  4093.92  3828.98  3979.96  632787.39410
2400  3/13/2024  3979.97  4083.00  3932.23  4004.79  482305.77660

[2401 rows x 6 columns]

In [8114]:
eth3 = eth3[["datetime", "close"]]
eth3

       datetime    close
0     8/17/2017   302.00
1     8/18/2017   293.96
2     8/19/2017   290.91
3     8/20/2017   299.10
4     8/21/2017   323.29
...         ...      ...
2396   3/9/2024  3905.21
2397  3/10/2024  3878.47
2398  3/11/2024  4064.80
2399  3/12/2024  3979.96
2400  3/13/2024  4004.79

[2401 rows x 2 columns]

In [8115]:
eth3 = eth3.rename(columns = {"datetime" : "Date", "close" : "Price"})
eth3

           Date    Price
0     8/17/2017   302.00
1     8/18/2017   293.96
2     8/19/2017   290.91
3     8/20/2017   299.10
4     8/21/2017   323.29
...         ...      ...
2396   3/9/2024  3905.21
2397  3/10/2024  3878.47
2398  3/11/2024  4064.80
2399  3/12/2024  3979.96
2400  3/13/2024  4004.79

[2401 rows x 2 columns]

In [8116]:
eth3["Date"] = pd.to_datetime(eth3["Date"], format = "%m/%d/%Y")
eth3["Date"] = eth3["Date"].dt.strftime("%m-%d-%Y")
eth3

            Date    Price
0     08-17-2017   302.00
1     08-18-2017   293.96
2     08-19-2017   290.91
3     08-20-2017   299.10
4     08-21-2017   323.29
...          ...      ...
2396  03-09-2024  3905.21
2397  03-10-2024  3878.47
2398  03-11-2024  4064.80
2399  03-12-2024  3979.96
2400  03-13-2024  4004.79

[2401 rows x 2 columns]

In [8117]:
eth4

            Date  Close/Last  Volume     Open     High      Low
0     04/06/2026     2107.81     NaN  2128.73  2119.17  2093.82
1     04/05/2026     2128.30     NaN  2056.47  2143.83  2110.33
2     04/04/2026     2056.71     NaN  2050.01  2065.51  2054.37
3     04/03/2026     2058.10     NaN  2038.58  2074.69  2042.35
4     04/02/2026     2052.71     NaN  2056.78  2062.47  2042.35
...          ...         ...     ...      ...      ...      ...
2298  03/12/2019      133.80     NaN   132.99   134.93   129.14
2299  03/11/2019      133.42     NaN   136.10   136.23   131.66
2300  03/10/2019      135.72     NaN   137.52   137.75   134.53
2301  03/09/2019      137.52     NaN   133.85   138.57   133.38
2302  03/08/2019      133.85     NaN   136.93   139.45   131.66

[2303 rows x 6 columns]

In [8118]:
eth4 = eth4.iloc[::-1]
eth4 = eth4.reset_index(drop = True)
eth4

            Date  Close/Last  Volume     Open     High      Low
0     03/08/2019      133.85     NaN   136.93   139.45   131.66
1     03/09/2019      137.52     NaN   133.85   138.57   133.38
2     03/10/2019      135.72     NaN   137.52   137.75   134.53
3     03/11/2019      133.42     NaN   136.10   136.23   131.66
4     03/12/2019      133.80     NaN   132.99   134.93   129.14
...          ...         ...     ...      ...      ...      ...
2298  04/02/2026     2052.71     NaN  2056.78  2062.47  2042.35
2299  04/03/2026     2058.10     NaN  2038.58  2074.69  2042.35
2300  04/04/2026     2056.71     NaN  2050.01  2065.51  2054.37
2301  04/05/2026     2128.30     NaN  2056.47  2143.83  2110.33
2302  04/06/2026     2107.81     NaN  2128.73  2119.17  2093.82

[2303 rows x 6 columns]

In [8119]:
eth4 = eth4[["Date", "Close/Last"]]
eth4 = eth4.rename(columns = {"Close/Last" : "Price"})
eth4

            Date    Price
0     03/08/2019   133.85
1     03/09/2019   137.52
2     03/10/2019   135.72
3     03/11/2019   133.42
4     03/12/2019   133.80
...          ...      ...
2298  04/02/2026  2052.71
2299  04/03/2026  2058.10
2300  04/04/2026  2056.71
2301  04/05/2026  2128.30
2302  04/06/2026  2107.81

[2303 rows x 2 columns]

In [8120]:
eth4["Date"] = pd.to_datetime(eth4["Date"], format = "%m/%d/%Y")
eth4["Date"] = eth4["Date"].dt.strftime("%m-%d-%Y")
eth4

            Date    Price
0     03-08-2019   133.85
1     03-09-2019   137.52
2     03-10-2019   135.72
3     03-11-2019   133.42
4     03-12-2019   133.80
...          ...      ...
2298  04-02-2026  2052.71
2299  04-03-2026  2058.10
2300  04-04-2026  2056.71
2301  04-05-2026  2128.30
2302  04-06-2026  2107.81

[2303 rows x 2 columns]

In [8121]:
eth = pd.concat([eth1, eth2], axis = "rows")
eth.drop_duplicates(subset = "Date", keep = "first")
eth = pd.concat([eth, eth3], axis = "rows")
eth.drop_duplicates(subset = "Date", keep = "first")
eth = pd.concat([eth, eth4], axis = "rows")
eth.drop_duplicates(subset = "Date", keep = "first")
#This is not working

            Date     Price
0     01-08-2015  0.753325
1     01-09-2015  0.701897
2     01-10-2015  0.708448
3     01-11-2015   1.06786
4     01-12-2015   1.21744
...          ...       ...
2298  04-02-2026   2052.71
2299  04-03-2026    2058.1
2300  04-04-2026   2056.71
2301  04-05-2026    2128.3
2302  04-06-2026   2107.81

[3738 rows x 2 columns]

In [8122]:
gold

            Date   Price    Open    High     Low  Volume  Chg%
0     2026-01-02  135793  136143  137037  135525   51877  0.02
1     2026-01-01  135771  135687  135850  135001   14622  0.23
2     2025-12-31  135454  136526  136527  134866   59050  1.10
3     2025-12-30  133974  133185  134880  132853   36733  1.04
4     2025-12-29  132595  137628  138269  131695   90640 -3.77
...          ...     ...     ...     ...     ...     ...   ...
3099  2014-01-06   29119   29300   29395   29051   24380 -0.55
3100  2014-01-04   29279   29279   29279   29279       0 -1.51
3101  2014-01-03   29727   30031   30125   29539    3050 -0.83
3102  2014-01-02   29975   29678   30050   29678    3140  1.47
3103  2014-01-01   29542   29435   29598   29340    2930  0.25

[3104 rows x 7 columns]

In [8123]:
gold = gold[["Date", "Price"]]
gold = gold.iloc[::-1]
gold = gold.reset_index(drop = True)
gold

            Date   Price
0     2014-01-01   29542
1     2014-01-02   29975
2     2014-01-03   29727
3     2014-01-04   29279
4     2014-01-06   29119
...          ...     ...
3099  2025-12-29  132595
3100  2025-12-30  133974
3101  2025-12-31  135454
3102  2026-01-01  135771
3103  2026-01-02  135793

[3104 rows x 2 columns]

In [8124]:
gold["Date"] = pd.to_datetime(gold["Date"], format = "%Y-%m-%d")
gold["Date"] = gold["Date"].dt.strftime("%m-%d-%Y")
gold

            Date   Price
0     01-01-2014   29542
1     01-02-2014   29975
2     01-03-2014   29727
3     01-04-2014   29279
4     01-06-2014   29119
...          ...     ...
3099  12-29-2025  132595
3100  12-30-2025  133974
3101  12-31-2025  135454
3102  01-01-2026  135771
3103  01-02-2026  135793

[3104 rows x 2 columns]

In [8125]:
appl

            Date Close/Last     Volume      Open      High       Low
0     04/06/2026    $258.86   29329910   $256.51   $262.16   $256.46
1     04/02/2026    $255.92   31289370   $254.20   $256.13   $250.65
2     04/01/2026    $255.63   40059430   $254.08   $256.18   $253.33
3     03/31/2026    $253.79   49598090   $247.91   $255.48  $247.101
4     03/30/2026    $246.63   39446210   $250.07   $250.87   $245.51
...          ...        ...        ...       ...       ...       ...
2508  04/13/2016     $28.01  131087040    $27.70   $28.085    $27.70
2509  04/12/2016     $27.61  108602280   $27.335   $27.625   $27.165
2510  04/11/2016    $27.255  117431760  $27.2425  $27.6525  $27.2075
2511  04/08/2016    $27.165   94215160  $27.2275  $27.4425  $27.0425
2512  04/07/2016    $27.135  126943240  $27.4875   $27.605  $27.0302

[2513 rows x 6 columns]

In [8126]:
appl = appl[["Date", "Close/Last"]]
appl

            Date Close/Last
0     04/06/2026    $258.86
1     04/02/2026    $255.92
2     04/01/2026    $255.63
3     03/31/2026    $253.79
4     03/30/2026    $246.63
...          ...        ...
2508  04/13/2016     $28.01
2509  04/12/2016     $27.61
2510  04/11/2016    $27.255
2511  04/08/2016    $27.165
2512  04/07/2016    $27.135

[2513 rows x 2 columns]

In [8127]:
appl["Close/Last"] = appl["Close/Last"].str.replace("$", "")
appl = appl.iloc[::-1]
appl = appl.reset_index(drop = True)
appl = appl.rename(columns = {"Close/Last" : "Price"})
appl["Date"] = pd.to_datetime(appl["Date"], format = "%m/%d/%Y")
appl["Date"] = appl["Date"].dt.strftime("%m-%d-%Y")
appl

/var/folders/_k/hbpmd3cn3cl4dn7css2gnbv80000gp/T/ipykernel_4023/3946404690.py:1: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  appl["Close/Last"] = appl["Close/Last"].str.replace("$", "")

            Date   Price
0     04-07-2016  27.135
1     04-08-2016  27.165
2     04-11-2016  27.255
3     04-12-2016   27.61
4     04-13-2016   28.01
...          ...     ...
2508  03-30-2026  246.63
2509  03-31-2026  253.79
2510  04-01-2026  255.63
2511  04-02-2026  255.92
2512  04-06-2026  258.86

[2513 rows x 2 columns]

In [8128]:
amzn = amzn[["Date", "Close/Last"]]
amzn["Close/Last"] = amzn["Close/Last"].str.replace("$", "")
amzn = amzn.iloc[::-1]
amzn = amzn.reset_index(drop = True)
amzn = amzn.rename(columns = {"Close/Last" : "Price"})
amzn["Date"] = pd.to_datetime(amzn["Date"], format = "%m/%d/%Y")
amzn["Date"] = amzn["Date"].dt.strftime("%m-%d-%Y")
amzn

            Date    Price
0     04-07-2016  29.5715
1     04-08-2016    29.73
2     04-11-2016  29.7965
3     04-12-2016  30.1585
4     04-13-2016   30.741
...          ...      ...
2508  03-30-2026   200.95
2509  03-31-2026   208.27
2510  04-01-2026   210.57
2511  04-02-2026   209.77
2512  04-06-2026   212.79

[2513 rows x 2 columns]

In [8129]:
comp = comp[["Date", "Close/Last"]]
#comp["Close/Last"] = comp["Close/Last"].str.replace("$", "")
comp = comp.iloc[::-1]
comp = comp.reset_index(drop = True)
comp = comp.rename(columns = {"Close/Last" : "Price"})
comp["Date"] = pd.to_datetime(comp["Date"], format = "%m/%d/%Y")
comp["Date"] = comp["Date"].dt.strftime("%m-%d-%Y")
comp

            Date     Price
0     04-07-2016   4848.37
1     04-08-2016   4850.69
2     04-11-2016   4833.40
3     04-12-2016   4872.09
4     04-13-2016   4947.42
...          ...       ...
2508  03-30-2026  20794.64
2509  03-31-2026  21590.63
2510  04-01-2026  21840.95
2511  04-02-2026  21879.18
2512  04-06-2026  21996.34

[2513 rows x 2 columns]

In [8130]:
googl = googl[["Date", "Close/Last"]]
googl["Close/Last"] = googl["Close/Last"].str.replace("$", "")
googl = googl.iloc[::-1]
googl = googl.reset_index(drop = True)
googl = googl.rename(columns = {"Close/Last" : "Price"})
googl["Date"] = pd.to_datetime(googl["Date"], format = "%m/%d/%Y")
googl["Date"] = googl["Date"].dt.strftime("%m-%d-%Y")
googl

            Date    Price
0     04-07-2016   38.006
1     04-08-2016  37.9735
2     04-11-2016   37.877
3     04-12-2016   38.216
4     04-13-2016  38.5955
...          ...      ...
2508  03-30-2026   273.50
2509  03-31-2026   287.56
2510  04-01-2026   297.39
2511  04-02-2026   295.77
2512  04-06-2026   299.99

[2513 rows x 2 columns]

In [8131]:
meta = meta[["Date", "Close/Last"]]
meta["Close/Last"] = meta["Close/Last"].str.replace("$", "")
meta = meta.iloc[::-1]
meta = meta.reset_index(drop = True)
meta = meta.rename(columns = {"Close/Last" : "Price"})
meta["Date"] = pd.to_datetime(meta["Date"], format = "%m/%d/%Y")
meta["Date"] = meta["Date"].dt.strftime("%m-%d-%Y")
meta

            Date   Price
0     04-07-2016  113.64
1     04-08-2016  110.63
2     04-11-2016  108.99
3     04-12-2016  110.61
4     04-13-2016  110.51
...          ...     ...
2508  03-30-2026  536.38
2509  03-31-2026  572.13
2510  04-01-2026  579.23
2511  04-02-2026  574.46
2512  04-06-2026  573.02

[2513 rows x 2 columns]

In [8132]:
msft = msft[["Date", "Close/Last"]]
msft["Close/Last"] = msft["Close/Last"].str.replace("$", "")
msft = msft.iloc[::-1]
msft = msft.reset_index(drop = True)
msft = msft.rename(columns = {"Close/Last" : "Price"})
msft["Date"] = pd.to_datetime(msft["Date"], format = "%m/%d/%Y")
msft["Date"] = msft["Date"].dt.strftime("%m-%d-%Y")
msft

            Date   Price
0     04-07-2016   54.46
1     04-08-2016   54.42
2     04-11-2016   54.31
3     04-12-2016   54.65
4     04-13-2016   55.35
...          ...     ...
2508  03-30-2026  358.96
2509  03-31-2026  370.17
2510  04-01-2026  369.37
2511  04-02-2026  373.46
2512  04-06-2026  372.88

[2513 rows x 2 columns]

In [8133]:
nvda = nvda[["Date", "Close/Last"]]
nvda["Close/Last"] = nvda["Close/Last"].str.replace("$", "")
nvda = nvda.iloc[::-1]
nvda = nvda.reset_index(drop = True)
nvda = nvda.rename(columns = {"Close/Last" : "Price"})
nvda["Date"] = pd.to_datetime(nvda["Date"], format = "%m/%d/%Y")
nvda["Date"] = nvda["Date"].dt.strftime("%m-%d-%Y")
nvda

            Date   Price
0     04-07-2016  0.8858
1     04-08-2016  0.8915
2     04-11-2016   0.897
3     04-12-2016   0.896
4     04-13-2016  0.9185
...          ...     ...
2508  03-30-2026  165.17
2509  03-31-2026  174.40
2510  04-01-2026  175.75
2511  04-02-2026  177.39
2512  04-06-2026  177.64

[2513 rows x 2 columns]

In [8134]:
tsla = tsla[["Date", "Close/Last"]]
tsla["Close/Last"] = tsla["Close/Last"].str.replace("$", "")
tsla = tsla.iloc[::-1]
tsla = tsla.reset_index(drop = True)
tsla = tsla.rename(columns = {"Close/Last" : "Price"})
tsla["Date"] = pd.to_datetime(tsla["Date"], format = "%m/%d/%Y")
tsla["Date"] = tsla["Date"].dt.strftime("%m-%d-%Y")
tsla

            Date    Price
0     04-07-2016  17.1467
1     04-08-2016  16.6713
2     04-11-2016  16.6613
3     04-12-2016  16.5213
4     04-13-2016  16.9687
...          ...      ...
2508  03-30-2026   355.28
2509  03-31-2026   371.75
2510  04-01-2026   381.26
2511  04-02-2026   360.59
2512  04-06-2026   352.82

[2513 rows x 2 columns]

In [8135]:
spcomp1 = pd.read_excel("S&P Composite.xlsx", skiprows = 6, nrows = 2519, usecols = "A:B")
spcomp1

     Effective date   S&P 500
0         2016-03-31  2059.74
1         2016-04-01  2072.78
2         2016-04-04  2066.13
3         2016-04-05  2045.17
4         2016-04-06  2066.66
...              ...      ...
2513      2026-03-30  6343.72
2514      2026-03-31  6528.52
2515      2026-04-01  6575.32
2516      2026-04-02  6582.69
2517      2026-04-06  6611.83

[2518 rows x 2 columns]

In [8136]:
spcomp1 = spcomp1.rename(columns = {"Effective date " : "Date", "S&P 500" : "Price"})
spcomp1

           Date    Price
0    2016-03-31  2059.74
1    2016-04-01  2072.78
2    2016-04-04  2066.13
3    2016-04-05  2045.17
4    2016-04-06  2066.66
...         ...      ...
2513 2026-03-30  6343.72
2514 2026-03-31  6528.52
2515 2026-04-01  6575.32
2516 2026-04-02  6582.69
2517 2026-04-06  6611.83

[2518 rows x 2 columns]

In [8137]:
spcomp1["Date"] = pd.to_datetime(spcomp1["Date"], format = "%Y-%m-%d")
spcomp1["Date"] = spcomp1["Date"].dt.strftime("%m-%d-%Y")
spcomp1

            Date    Price
0     03-31-2016  2059.74
1     04-01-2016  2072.78
2     04-04-2016  2066.13
3     04-05-2016  2045.17
4     04-06-2016  2066.66
...          ...      ...
2513  03-30-2026  6343.72
2514  03-31-2026  6528.52
2515  04-01-2026  6575.32
2516  04-02-2026  6582.69
2517  04-06-2026  6611.83

[2518 rows x 2 columns]

In [8138]:
spcomp2

            Date   S&P500
0     12/22/2014  2078.54
1     12/23/2014  2082.17
2     12/24/2014  2081.88
3     12/26/2014  2088.77
4     12/29/2014  2090.57
...          ...      ...
2512  12/16/2024  6074.08
2513  12/17/2024  6050.61
2514  12/18/2024  5872.16
2515  12/19/2024  5867.08
2516  12/20/2024  5930.85

[2517 rows x 2 columns]

In [8139]:
spcomp2["Date"] = pd.to_datetime(spcomp2["Date"], format = "%m/%d/%Y")
spcomp2["Date"] = spcomp2["Date"].dt.strftime("%m-%d-%Y")
spcomp2 = spcomp2.rename(columns = {"S&P500" : "Price"})
spcomp2
#I probably will not use this one

            Date    Price
0     12-22-2014  2078.54
1     12-23-2014  2082.17
2     12-24-2014  2081.88
3     12-26-2014  2088.77
4     12-29-2014  2090.57
...          ...      ...
2512  12-16-2024  6074.08
2513  12-17-2024  6050.61
2514  12-18-2024  5872.16
2515  12-19-2024  5867.08
2516  12-20-2024  5930.85

[2517 rows x 2 columns]

In [8140]:
spgold

            Date     Open     High      Low    Close
0       4/2/2026  2724.56  2724.56  2724.56  2724.56
1       4/1/2026  2802.22  2802.22  2802.22  2802.22
2      3/31/2026  2723.92  2723.92  2723.92  2723.92
3      3/30/2026  2653.41  2653.41  2653.41  2653.41
4      3/27/2026  2634.08  2634.08  2634.08  2634.08
...          ...      ...      ...      ...      ...
4332    1/7/2009   490.04   490.04   490.04   490.04
4333    1/6/2009   504.19   504.19   504.19   504.19
4334    1/5/2009   499.42   499.42   499.42   499.42
4335    1/2/2009   512.05   512.05   512.05   512.05
4336  12/31/2008   514.85   514.85   514.85   514.85

[4337 rows x 5 columns]

In [8141]:
spgold = spgold[["Date", " Close"]]
spgold = spgold.rename(columns = {" Close" : "Price"})
spgold

            Date    Price
0       4/2/2026  2724.56
1       4/1/2026  2802.22
2      3/31/2026  2723.92
3      3/30/2026  2653.41
4      3/27/2026  2634.08
...          ...      ...
4332    1/7/2009   490.04
4333    1/6/2009   504.19
4334    1/5/2009   499.42
4335    1/2/2009   512.05
4336  12/31/2008   514.85

[4337 rows x 2 columns]

In [8142]:
spgold["Date"] = pd.to_datetime(spgold["Date"], format = "%m/%d/%Y")
spgold["Date"] = spgold["Date"].dt.strftime("%m-%d-%Y")
spgold = spgold.iloc[::-1]
spgold = spgold.reset_index(drop = True)
spgold

            Date    Price
0     12-31-2008   514.85
1     01-02-2009   512.05
2     01-05-2009   499.42
3     01-06-2009   504.19
4     01-07-2009   490.04
...          ...      ...
4332  03-27-2026  2634.08
4333  03-30-2026  2653.41
4334  03-31-2026  2723.92
4335  04-01-2026  2802.22
4336  04-02-2026  2724.56

[4337 rows x 2 columns]

In [8143]:
silver1

,Date,Open,High,Low,Close,Volume,ticker,name
0,2000-08-30 00:00:00-04:00,4.950000,4.950000,4.895000,4.930000,2319,SI=F,Silver Futures (SI=F)
1,2000-08-31 00:00:00-04:00,4.920000,5.045000,4.920000,5.003000,1612,SI=F,Silver Futures (SI=F)
2,2000-09-01 00:00:00-04:00,5.035000,5.035000,4.985000,5.004000,1375,SI=F,Silver Futures (SI=F)
3,2000-09-05 00:00:00-04:00,4.990000,5.005000,4.975000,4.998000,856,SI=F,Silver Futures (SI=F)
4,2000-09-06 00:00:00-04:00,5.000000,5.000000,4.980000,4.983000,232,SI=F,Silver Futures (SI=F)
...,...,...,...,...,...,...,...,...
6355,2025-12-24 00:00:00-05:00,71.514999,71.514999,71.000000,71.030998,35,SI=F,Silver Futures (SI=F)
6356,2025-12-26 00:00:00-05:00,74.500000,78.839996,73.735001,76.486000,140,SI=F,Silver Futures (SI=F)
6357,2025-12-29 00:00:00-05:00,79.699997,79.699997,69.856003,69.856003,1608,SI=F,Silver Futures (SI=F)
6358,2025-12-30 00:00:00-05:00,71.330002,77.410004,70.500000,77.374001,1608,SI=F,Silver Futures (SI=F)
6359,2025-12-31 00:00:00-05:00,76.065002,76.275002,70.224998,71.139999,110555,SI=F,Silver Futures (SI=F)

In [8144]:
silver1 = silver1[["Date", "Close"]]
silver1 = silver1.rename(columns = {"Close" : "Price"})
silver1

                           Date      Price
0     2000-08-30 00:00:00-04:00   4.930000
1     2000-08-31 00:00:00-04:00   5.003000
2     2000-09-01 00:00:00-04:00   5.004000
3     2000-09-05 00:00:00-04:00   4.998000
4     2000-09-06 00:00:00-04:00   4.983000
...                         ...        ...
6355  2025-12-24 00:00:00-05:00  71.030998
6356  2025-12-26 00:00:00-05:00  76.486000
6357  2025-12-29 00:00:00-05:00  69.856003
6358  2025-12-30 00:00:00-05:00  77.374001
6359  2025-12-31 00:00:00-05:00  71.139999

[6360 rows x 2 columns]

In [8145]:
silver1["Date"] = silver1["Date"].str.slice(stop = 19)
silver1

                     Date      Price
0     2000-08-30 00:00:00   4.930000
1     2000-08-31 00:00:00   5.003000
2     2000-09-01 00:00:00   5.004000
3     2000-09-05 00:00:00   4.998000
4     2000-09-06 00:00:00   4.983000
...                   ...        ...
6355  2025-12-24 00:00:00  71.030998
6356  2025-12-26 00:00:00  76.486000
6357  2025-12-29 00:00:00  69.856003
6358  2025-12-30 00:00:00  77.374001
6359  2025-12-31 00:00:00  71.139999

[6360 rows x 2 columns]

In [8146]:
silver1["Date"] = pd.to_datetime(silver1["Date"], format = "%Y-%m-%d %H:%M:%S")
silver1["Date"] = silver1["Date"].dt.strftime("%m-%d-%Y")
silver1

            Date      Price
0     08-30-2000   4.930000
1     08-31-2000   5.003000
2     09-01-2000   5.004000
3     09-05-2000   4.998000
4     09-06-2000   4.983000
...          ...        ...
6355  12-24-2025  71.030998
6356  12-26-2025  76.486000
6357  12-29-2025  69.856003
6358  12-30-2025  77.374001
6359  12-31-2025  71.139999

[6360 rows x 2 columns]

In [8147]:
silver2

           Date    Open    High     Low   Close
0    04/06/2026  72.720  73.735  71.335  72.847
1    04/02/2026  75.150  75.985  69.610  72.924
2    04/01/2026  75.480  76.265  74.000  76.078
3    03/31/2026  70.245  75.625  69.100  74.919
4    03/30/2026  69.350  72.025  67.700  70.569
..          ...     ...     ...     ...     ...
249  04/11/2025  31.115  32.210  30.865  31.910
250  04/10/2025  30.990  31.245  30.510  30.759
251  04/09/2025  29.780  31.065  29.255  30.415
252  04/08/2025  30.090  30.520  29.560  29.686
253  04/07/2025  29.230  30.760  27.520  29.604

[254 rows x 5 columns]

In [8148]:
silver2 = silver2[["Date", "Close"]]
silver2 = silver2.rename(columns = {"Close" : "Price"})
silver2

           Date   Price
0    04/06/2026  72.847
1    04/02/2026  72.924
2    04/01/2026  76.078
3    03/31/2026  74.919
4    03/30/2026  70.569
..          ...     ...
249  04/11/2025  31.910
250  04/10/2025  30.759
251  04/09/2025  30.415
252  04/08/2025  29.686
253  04/07/2025  29.604

[254 rows x 2 columns]

In [8149]:
silver2 = silver2.iloc[::-1]
silver2 = silver2.reset_index(drop = True)
silver2

           Date   Price
0    04/07/2025  29.604
1    04/08/2025  29.686
2    04/09/2025  30.415
3    04/10/2025  30.759
4    04/11/2025  31.910
..          ...     ...
249  03/30/2026  70.569
250  03/31/2026  74.919
251  04/01/2026  76.078
252  04/02/2026  72.924
253  04/06/2026  72.847

[254 rows x 2 columns]

In [8150]:
silver2["Date"] = pd.to_datetime(silver2["Date"], format = "%m/%d/%Y")
silver2["Date"] = silver2["Date"].dt.strftime("%m-%d-%Y")
silver2

           Date   Price
0    04-07-2025  29.604
1    04-08-2025  29.686
2    04-09-2025  30.415
3    04-10-2025  30.759
4    04-11-2025  31.910
..          ...     ...
249  03-30-2026  70.569
250  03-31-2026  74.919
251  04-01-2026  76.078
252  04-02-2026  72.924
253  04-06-2026  72.847

[254 rows x 2 columns]

In [8151]:
silver = pd.concat([silver1, silver2], axis = "rows")
eth.drop_duplicates(subset = "Date", keep = "first")
silver

           Date   Price
0    08-30-2000   4.930
1    08-31-2000   5.003
2    09-01-2000   5.004
3    09-05-2000   4.998
4    09-06-2000   4.983
..          ...     ...
249  03-30-2026  70.569
250  03-31-2026  74.919
251  04-01-2026  76.078
252  04-02-2026  72.924
253  04-06-2026  72.847

[6614 rows x 2 columns]

In [8152]:
solana1

,datetime,open,high,low,close,volume,Unnamed: 6,Unnamed: 7,Unnamed: 8,Unnamed: 9,Unnamed: 10
0,8/11/2020,2.8500,3.5208,2.8433,3.2985,1552384.78,NaN,NaN,NaN,NaN,NaN
1,8/12/2020,3.2985,3.9289,3.0800,3.7558,1737042.95,NaN,NaN,NaN,NaN,NaN
2,8/13/2020,3.7500,4.1387,3.5003,3.7300,1685759.24,NaN,NaN,NaN,NaN,NaN
3,8/14/2020,3.7207,3.7676,3.3210,3.4099,1474161.79,NaN,NaN,NaN,NaN,NaN
4,8/15/2020,3.4181,3.7400,3.1500,3.1730,1070233.20,NaN,NaN,NaN,NaN,NaN
...,...,...,...,...,...,...,...,...,...,...,...
1306,3/9/2024,144.7900,149.1500,143.5400,144.2900,3686876.81,NaN,NaN,NaN,NaN,NaN
1307,3/10/2024,144.3000,148.5000,140.4300,144.3900,4489519.25,NaN,NaN,NaN,NaN,NaN
1308,3/11/2024,144.3900,150.2000,136.4900,148.8300,7743384.35,NaN,NaN,NaN,NaN,NaN
1309,3/12/2024,148.8300,155.0000,141.5000,151.0500,8930538.00,NaN,NaN,NaN,NaN,NaN
1310,3/13/2024,151.0600,166.7300,148.7100,163.9000,7627285.95,NaN,NaN,NaN,NaN,NaN

In [8153]:
solana1 = solana1[["datetime", "close"]]
solana1 = solana1.rename(columns = {"datetime" : "Date", "close" : "Price"})
solana1

           Date     Price
0     8/11/2020    3.2985
1     8/12/2020    3.7558
2     8/13/2020    3.7300
3     8/14/2020    3.4099
4     8/15/2020    3.1730
...         ...       ...
1306   3/9/2024  144.2900
1307  3/10/2024  144.3900
1308  3/11/2024  148.8300
1309  3/12/2024  151.0500
1310  3/13/2024  163.9000

[1311 rows x 2 columns]

In [8154]:
solana1["Date"] = pd.to_datetime(solana1["Date"], format = "%m/%d/%Y")
solana1["Date"] = solana1["Date"].dt.strftime("%m-%d-%Y")
solana1

            Date     Price
0     08-11-2020    3.2985
1     08-12-2020    3.7558
2     08-13-2020    3.7300
3     08-14-2020    3.4099
4     08-15-2020    3.1730
...          ...       ...
1306  03-09-2024  144.2900
1307  03-10-2024  144.3900
1308  03-11-2024  148.8300
1309  03-12-2024  151.0500
1310  03-13-2024  163.9000

[1311 rows x 2 columns]

In [8155]:
solana2

            Date  Close/Last  Volume     Open     High      Low
0     04/05/2026      81.968     NaN   80.545   82.903   81.689
1     04/04/2026      80.548     NaN   80.177   80.833   80.379
2     04/03/2026      79.852     NaN   78.895   80.197   78.893
3     04/02/2026      79.120     NaN   79.006   79.761   78.893
4     04/01/2026      79.011     NaN   83.377   81.760   78.395
...          ...         ...     ...      ...      ...      ...
1304  02/04/2022     115.587     NaN  102.527  115.856  110.340
1305  02/03/2022     102.437     NaN   98.188  103.842  100.388
1306  02/02/2022      98.576     NaN  109.298  103.073   96.848
1307  02/01/2022     109.519     NaN  106.139  112.137  108.338
1308  01/31/2022     105.630     NaN   89.892  108.008   99.236

[1309 rows x 6 columns]

In [8156]:
solana2 = solana2[["Date", "Close/Last"]]
solana2 = solana2.rename(columns = {"Close/Last" : "Price"})
solana2

            Date    Price
0     04/05/2026   81.968
1     04/04/2026   80.548
2     04/03/2026   79.852
3     04/02/2026   79.120
4     04/01/2026   79.011
...          ...      ...
1304  02/04/2022  115.587
1305  02/03/2022  102.437
1306  02/02/2022   98.576
1307  02/01/2022  109.519
1308  01/31/2022  105.630

[1309 rows x 2 columns]

In [8157]:
solana2 = solana2.iloc[::-1]
solana2 = solana2.reset_index(drop = True)
solana2

            Date    Price
0     01/31/2022  105.630
1     02/01/2022  109.519
2     02/02/2022   98.576
3     02/03/2022  102.437
4     02/04/2022  115.587
...          ...      ...
1304  04/01/2026   79.011
1305  04/02/2026   79.120
1306  04/03/2026   79.852
1307  04/04/2026   80.548
1308  04/05/2026   81.968

[1309 rows x 2 columns]

In [8158]:
solana2["Date"] = pd.to_datetime(solana2["Date"], format = "%m/%d/%Y")
solana2["Date"] = solana2["Date"].dt.strftime("%m-%d-%Y")
solana2

            Date    Price
0     01-31-2022  105.630
1     02-01-2022  109.519
2     02-02-2022   98.576
3     02-03-2022  102.437
4     02-04-2022  115.587
...          ...      ...
1304  04-01-2026   79.011
1305  04-02-2026   79.120
1306  04-03-2026   79.852
1307  04-04-2026   80.548
1308  04-05-2026   81.968

[1309 rows x 2 columns]

In [8159]:
solana = pd.concat([solana1, solana2], axis = "rows")
solana.drop_duplicates(subset = "Date", keep = "first")
solana

            Date    Price
0     08-11-2020   3.2985
1     08-12-2020   3.7558
2     08-13-2020   3.7300
3     08-14-2020   3.4099
4     08-15-2020   3.1730
...          ...      ...
1304  04-01-2026  79.0110
1305  04-02-2026  79.1200
1306  04-03-2026  79.8520
1307  04-04-2026  80.5480
1308  04-05-2026  81.9680

[2620 rows x 2 columns]

In [8160]:
xmag

           Date  Close/Last  Volume   Open     High      Low
0    04/10/2026     22.9731   39999  23.16  23.2199  22.9400
1    04/09/2026     23.1250   47840  23.05  23.1800  22.9500
2    04/08/2026     23.0421   31146  22.99  23.1300  22.9001
3    04/07/2026     22.5000   19290  22.49  22.5200  22.3300
4    04/06/2026     22.5047   60402  22.43  22.5799  22.3700
..          ...         ...     ...    ...      ...      ...
362  10/28/2024     19.8400   81785  19.98  19.9800  19.8101
363  10/25/2024     19.7700  165791  20.01  20.0100  19.7311
364  10/24/2024     19.8300   36263  20.14  20.1400  19.8000
365  10/23/2024     19.8758   74207  20.48  20.4800  19.7800
366  10/22/2024     20.0000   64844  19.97  20.0100  19.8900

[367 rows x 6 columns]

In [8161]:
xmag = xmag[["Date", "Close/Last"]]
xmag = xmag.rename(columns = {"Close/Last" : "Price"})
xmag

           Date    Price
0    04/10/2026  22.9731
1    04/09/2026  23.1250
2    04/08/2026  23.0421
3    04/07/2026  22.5000
4    04/06/2026  22.5047
..          ...      ...
362  10/28/2024  19.8400
363  10/25/2024  19.7700
364  10/24/2024  19.8300
365  10/23/2024  19.8758
366  10/22/2024  20.0000

[367 rows x 2 columns]

In [8162]:
xmag = xmag.iloc[::-1]
xmag = xmag.reset_index(drop = True)
xmag

           Date    Price
0    10/22/2024  20.0000
1    10/23/2024  19.8758
2    10/24/2024  19.8300
3    10/25/2024  19.7700
4    10/28/2024  19.8400
..          ...      ...
362  04/06/2026  22.5047
363  04/07/2026  22.5000
364  04/08/2026  23.0421
365  04/09/2026  23.1250
366  04/10/2026  22.9731

[367 rows x 2 columns]

In [8163]:
xmag["Date"] = pd.to_datetime(xmag["Date"], format = "%m/%d/%Y")
xmag["Date"] = xmag["Date"].dt.strftime("%m-%d-%Y")
xmag

           Date    Price
0    10-22-2024  20.0000
1    10-23-2024  19.8758
2    10-24-2024  19.8300
3    10-25-2024  19.7700
4    10-28-2024  19.8400
..          ...      ...
362  04-06-2026  22.5047
363  04-07-2026  22.5000
364  04-08-2026  23.0421
365  04-09-2026  23.1250
366  04-10-2026  22.9731

[367 rows x 2 columns]